package nl.rickrongen.auction.auction;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-31T11:36:14.227+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "AuctionService", 
                  wsdlLocation = "http://localhost:8080/Auction?WSDL",
                  targetNamespace = "http://web.auction/") 
public class AuctionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.auction/", "AuctionService");
    public final static QName AuctionPort = new QName("http://web.auction/", "AuctionPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Auction?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuctionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Auction?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public AuctionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuctionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuctionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AuctionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuctionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuctionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Auction
     */
    @WebEndpoint(name = "AuctionPort")
    public Auction getAuctionPort() {
        return super.getPort(AuctionPort, Auction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Auction
     */
    @WebEndpoint(name = "AuctionPort")
    public Auction getAuctionPort(WebServiceFeature... features) {
        return super.getPort(AuctionPort, Auction.class, features);
    }

}
