package nl.rickrongen.auction.auction;

import nl.rickrongen.auction.shared.User;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-31T11:36:14.211+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://web.auction/", name = "Auction")
@XmlSeeAlso({ObjectFactory.class})
public interface Auction {

    @WebMethod
    @Action(input = "http://web.auction/Auction/newBidRequest", output = "http://web.auction/Auction/newBidResponse")
    @RequestWrapper(localName = "newBid", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.NewBid")
    @ResponseWrapper(localName = "newBidResponse", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.NewBidResponse")
    @WebResult(name = "return", targetNamespace = "")
    public nl.rickrongen.auction.auction.Bid newBid(
        @WebParam(name = "arg0", targetNamespace = "")
        nl.rickrongen.auction.auction.Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
                User arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        nl.rickrongen.auction.auction.Money arg2
    );

    @WebMethod
    @Action(input = "http://web.auction/Auction/offerItemRequest", output = "http://web.auction/Auction/offerItemResponse")
    @RequestWrapper(localName = "offerItem", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.OfferItem")
    @ResponseWrapper(localName = "offerItemResponse", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.OfferItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public nl.rickrongen.auction.auction.Item offerItem(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        nl.rickrongen.auction.auction.Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://web.auction/Auction/revokeItemRequest", output = "http://web.auction/Auction/revokeItemResponse")
    @RequestWrapper(localName = "revokeItem", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.RevokeItem")
    @ResponseWrapper(localName = "revokeItemResponse", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.RevokeItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean revokeItem(
        @WebParam(name = "arg0", targetNamespace = "")
        nl.rickrongen.auction.auction.Item arg0
    );

    @WebMethod
    @Action(input = "http://web.auction/Auction/findItemByDescriptionRequest", output = "http://web.auction/Auction/findItemByDescriptionResponse")
    @RequestWrapper(localName = "findItemByDescription", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.FindItemByDescription")
    @ResponseWrapper(localName = "findItemByDescriptionResponse", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.FindItemByDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<nl.rickrongen.auction.auction.Item> findItemByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://web.auction/Auction/getItemRequest", output = "http://web.auction/Auction/getItemResponse")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://web.auction/", className = "nl.rickrongen.auction.auction.GetItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public nl.rickrongen.auction.auction.Item getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );
}
