package nl.rickrongen.auction.registration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-05-31T11:36:04.575+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "RegistrationService", 
                  wsdlLocation = "http://localhost:8080/Registration?WSDL",
                  targetNamespace = "http://web.auction/") 
public class RegistrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.auction/", "RegistrationService");
    public final static QName RegistrationPort = new QName("http://web.auction/", "RegistrationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Registration?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Registration?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public RegistrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RegistrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RegistrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RegistrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Registration
     */
    @WebEndpoint(name = "RegistrationPort")
    public Registration getRegistrationPort() {
        return super.getPort(RegistrationPort, Registration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Registration
     */
    @WebEndpoint(name = "RegistrationPort")
    public Registration getRegistrationPort(WebServiceFeature... features) {
        return super.getPort(RegistrationPort, Registration.class, features);
    }

}
